name: photoextractor-prod

services:
  backend:
    container_name: backend_prod
    networks:
      - prod
    build:
      context: ../backend
      dockerfile: Dockerfile
    expose:
      - "8080"
    restart: unless-stopped

  frontend:
    container_name: frontend_prod
    networks:
      - prod
    build:
      context: ../frontend
      dockerfile: Dockerfile
    ports:
      - "3000:8080"
    depends_on:
      - backend
    restart: unless-stopped

networks:
  prod:
    name: photoextractor_prod
    external: true
