listeners.tcp.default = 5672

default_user  = ${RABBITMQ_USER}
default_pass  = ${RABBITMQ_PASS}
default_vhost = ${RABBITMQ_VHOST}

log.console = true
log.console.level = info
log.file = false

disk_free_limit.absolute = 2G
