# syntax=docker/dockerfile:1

FROM golang:1.25.7-alpine3.23

WORKDIR /app

RUN apk add --no-cache git

# air для hot reload
RUN go install github.com/air-verse/air@latest

COPY go.mod go.sum ./
RUN go mod download

COPY . .

EXPOSE 8080

CMD ["air", "-c", ".air.toml"]